# name: Build ASP.NET Core

# on:
  # push:
    # branches:
      # - main

# jobs:
  # build:

    # runs-on: ubuntu-latest

    # steps:

    # - name: Checkout Repository
      # uses: actions/checkout@v4

    # - name: Setup .NET
      # uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: '8.0.x'

    # - name: Restore Packages
      # run: dotnet restore

    # - name: Build Project
      # run: dotnet build --configuration Release --no-restore
      
      
 # "Create a workflow called 'Build ASP.NET Core'. Whenever someone pushes code to the main branch, start a job named build. Run that job on GitHub's latest Ubuntu machine. First, download (checkout) my repository. Then install the .NET 8 SDK. Next, restore all NuGet packages. Finally, build the project in Release mode without restoring packages again."   

# When code is pushed to main,
# GitHub creates an Ubuntu VM,
# downloads my project,
# installs .NET 8,
# restores packages,
# builds the application,
# and tells me whether the build succeeded or failed. 

# name: Build ASP.NET Core

# on:
  # push:
    # branches:
      # - main

# jobs:
  # build:

    # runs-on: ubuntu-latest

    # steps:

    # - name: Checkout Repository
      # uses: actions/checkout@v4

    # - name: Setup .NET
      # uses: actions/setup-dotnet@v4
      # with:
        # dotnet-version: '8.0.x'

    # - name: Restore Packages
      # run: dotnet restore

    # - name: Build Project
      # run: dotnet build --configuration Release --no-restore

    # - name: Publish Project
      # run: dotnet publish -c Release -o publish

    # - name: Upload Build Artifact
      # uses: actions/upload-artifact@v4
      # with:
        # name: NewTASUI
        # path: publish
        
# When someone pushes to the main branch, create an Ubuntu machine, download my repository, install .NET 8, restore packages, build the application, publish it into a folder called publish, upload that folder to GitHub as an artifact, and then delete the Ubuntu machine.        

name: Build ASP.NET Core

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository                                                     #Checkout downloads your repository.
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Packages NewTASUI.csproj                                        #downloads NuGet Packages
      run: dotnet restore NewTASUI.csproj

    - name: Build Project                                                           #Compiles your code. Produces DLLs.
      run: dotnet build NewTASUI.csproj --configuration Release --no-restore

    - name: Publish Project                                                         #Create deployable application
      run: dotnet publish NewTASUI.csproj -c Release -o publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NewTASUI
        path: publish
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker Image from Dockerfile
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/newtasui:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/newtasui:latest
    
    # - name: Test SSH Connection to Azure
      # uses: appleboy/ssh-action@v1.2.0
      # with:
        # host: ${{ secrets.AZURE_HOST }}
        # username: ${{ secrets.AZURE_USER }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        # script: |
          # echo "Connected Successfully"
          # hostname
          # pwd
          # whoami    
    - name: Verify Repository Files
      run: |
        pwd
        echo "=========================="
        ls -la
        echo "=========================="
        find . -maxdepth 3
 
    - name: Copy Production Compose File
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-compose.prod.yml,nginx"
        target: "/home/azureuser/"    
      
    - name: Deploy Latest Image to Azure VM
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/azureuser
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --remove-orphans     
      
      # Whenever someone pushes to the main branch, GitHub creates a temporary Ubuntu virtual machine, downloads my repository, installs the .NET SDK, restores all NuGet packages, builds the application, publishes it, uploads the published files as an artifact, logs into Docker Hub using encrypted credentials, builds a Docker image from my Dockerfile, pushes that image to Docker Hub, and finally deletes the temporary runner.